### ISSUE TITLE
Update to Allure 1.4.x

### ISSUE THREAD

**Issue by vania-pooh** [allure-framework/karma-allure-reporter#2]
1) Implement JS Adapter API
2) Update this adapter to use this API

**Comment by ctapobep** [comment]
Any updates on this activity?

**Comment by just-boris** [comment]
@ctapobep hello. I'm in work with this reporter again. 
Could you please try to use this new version?

You need to install it directly from master branch:
```
npm install git+https://github.com/allure-framework/karma-allure-reporter.git
```
This version haven't released yet, but it will be after I make a few tests.

**Comment by ctapobep** [comment]
I tried it out and it worked, looking forward to see the package in NPM repo.
Sorry for late feedback.

**Comment by just-boris** [comment]
Successfully published
